# Generated by Django 5.2.1 on 2025-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login_location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_time",
        ),
        migrations.RemoveField(
            model_name="user",
            name="signup_location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="signup_time",
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="avatar/default.jpg",
                null=True,
                upload_to="avatar",
                verbose_name="用户头像",
            ),
        ),
        migrations.AlterModelTable(
            name="foodinfo",
            table="foodinfo",
        ),
    ]
